#%RAML 1.0
title: Sandbox API
version: v1
baseUri: /api/v1

types:
    ContextUserResponse:
        type: object
        properties:
            success: boolean
            isAuthenticated: boolean
            user: User | nil
    LoginInput:
        type: object
        properties:
            email:
                type: string
                required: true
            password:
                type: string
                required: true
    LoginUnauthorized:
        type: object 
        properties:
            message: string
    LoginResponse:
        type: object 
        properties:
            success: boolean
            accessToken: string | nil
            user: User | nil 
    User:
        type: object
        properties:
            id: string
            name: string
    UserList:
        type: object
        properties:
            users: User[]
    UserInput:
        type: object
        properties:
            name:
                type: string
                required: true

/auth:
    /me:
        get:
            description: Get the context user
            responses:
                200:
                    body:
                        application/json:
                            type: ContextUserResponse
    /login:
        post:
            description: Authenticate to application
            body:
                application/json:
                    type: LoginInput
            responses:
                200:
                    body:
                        application/json:
                            type: LoginResponse
                401:
                    body:
                        application/json:
                            type: LoginUnauthorized
                            example: |
                                { "message": "Unauthorized" }
/users:
    get:
        description: Get the list of users
        responses:
            200:
                body:
                    application/json:
                        type: UserList
    post:
        description: Create a users
        body:
            application/json:
                type: UserInput
        responses:
            201:
                body:
                    application/json:
                        type: User

/users/{id}:
    uriParameters:
        id: string
    get:
        description: Get a single user
        responses:
            200:
                body:
                    application/json:
                        type: User

