#%RAML 1.0 Overlay
extends: ./api.raml

uses:
    luvio: luvio://annotations.raml

(luvio.keyPrefix): 'sandboxapi'
(luvio.ttl): 30000

types:
    User:
        (luvio.key):
            userid: id
        (luvio.opaque): true
        (luvio.ttl): 20000

/users:
    get:
        (luvio.adapter):
            name: getUsers
    post:
        (luvio.adapter):
            name: createUser
