#%RAML 1.0 Overlay
extends: ./api.raml

uses:
    luvio: luvio://annotations.raml

(luvio.keyPrefix): 'sandboxapi'
(luvio.ttl): 30000

types:
    ContextUserResponse:
        (luvio.ttl): 5000
    User:
        (luvio.key):
            id: id
        (luvio.opaque): true
        (luvio.ttl): 20000
    AuthResponse:
        (luvio.key):
            accessToken: accessToken

/auth:
    /me:
        get:
            (luvio.adapter):
                name: getContextUser
    /login:
        post:
            (luvio.adapter):
                name: login
    /logout:
        post:
            (luvio.adapter):
                name: logout
/users:
    get:
        (luvio.adapter):
            name: getUsers
    post:
        (luvio.adapter):
            name: createUser

    /{id}:
        get:
            (luvio.adapter):
                name: getUser
            (luvio.key):
                id: urlParams.id
